steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login ${_HOSTNAME} --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker buildx create --use']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker buildx build --build-arg BASE_IMAGE=${_BASE_IMAGE} -t $$USERNAME/${REPO_NAME}:${TAG_NAME} --platform=${_PLATFORM} ${_ARGS} --cpuset-cpus=1 --push .']
   secretEnv: ['USERNAME']
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/davod-org/secrets/docker-password/versions/1
      env: PASSWORD
    - versionName: projects/davod-org/secrets/docker-username/versions/1
      env: USERNAME
